version: '3.7'
services:
  app:
    container_name: app-miprestamoapi
    image: app-miprestamoapi
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    container_name: postgresql-app-miprestamoapi
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=p0stgr3sql
      - POSTGRES_USER=postgres
      - POSTGRES_DB=miprestamodb